	#DEFINE GOFISH_APP_NAME 'GoFish'
	#DEFINE GOFISH_APP_FILE  'GoFish.app'
	#DEFINE GOFISH_VERSION '7.1.30'
	#DEFINE GOFISH_BUILDDATE 'November 01, 2024'
	#DEFINE GOFISH_DBUILDDATE Date(2024,11, 1)
	#DEFINE GOFISH_DOWNLOAD_URL 'https://raw.githubusercontent.com/VFPX/GoFish/master/Source/Source.zip'
	#DEFINE GOFISH_VERSION_STRING_FOR_VERSION_FILE 'GoFish - 7.1.30 - November 01, 2024 - 20241101'
	#DEFINE THOR_TOOL_NAME	'Thor_Tool_GoFish'
	#DEFINE VERSON_FILE_URL	'https://github.com/VFPX/GoFish/_GoFishVersionFile.txt'
	#DEFINE VERSION_LOCAL_FILE 'GoFishVersionFile.txt'
	#DEFINE GOFISH_HOME_PAGE 'https://github.com/VFPX/GoFish'
